// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijisnaikxsnxlmwsexmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqaXNuYWlreHNueGxtd3NleG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDk0NTEsImV4cCI6MjA3MDc4NTQ1MX0.kyuVej9XgXgkY7usZMybRmRQgP3YzhMK88K_sf-pVHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});